<?php
/**
 * Snippet Name: AWS Origin Hiding Verification
 * Description: Verifies x-aws-pass header generated by aws-lambda-edge-origin-hiding.js for origin-hiding protection.
 * Does NOT verify that the IP is in the MPL; Lambda@Edge already did that
 * Author: Security Automation
 */

add_action('init', function () {
    $secret = 'your-secret-string-here'; // Must match Lambda env var SHARED_SECRET

    $header = $_SERVER['HTTP_X_AWS_PASS'] ?? '';
    if (!$header) {
        status_header(403);
        exit('Forbidden - Missing signature header');
    }

    // Expected format: <base64-hmac>.<timestamp>.<nonce>
    [$hmac, $timestamp, $nonce] = explode('.', $header, 3) + [null, null, null];
    if (!$hmac || !$timestamp || !$nonce) {
        status_header(403);
        exit('Forbidden - Invalid signature format');
    }

    // Require that REMOTE_ADDR exists and is a valid IP
    $remote_ip = $_SERVER['REMOTE_ADDR'] ?? '';
    if (!filter_var($remote_ip, FILTER_VALIDATE_IP)) {
        status_header(403);
        exit('Forbidden - Invalid IP address');
    }

    // Reject expired timestamp (5 min window)
    if (abs(time() - (int) $timestamp) > 300) {
        status_header(403);
        exit('Forbidden - Signature expired');
    }

    // Verify HMAC
    $user_agent = $_SERVER['HTTP_USER_AGENT'] ?? '';
    $payload = "{$user_agent}|{$nonce}|{$timestamp}";
    $calc_hmac = base64_encode(hash_hmac('sha256', $payload, $secret, true));

    if (!hash_equals($hmac, $calc_hmac)) {
        status_header(403);
        exit('Forbidden - Invalid signature');
    }
});
